#!/usr/bin/env python3
"""Offline, checked v3 -> v4 B1 migration. Never edits the original state."""
import argparse
import contextlib
import copy
import fcntl
import json
import os
from pathlib import Path
import shutil
import sqlite3
import subprocess
import sys
import tempfile

from completion_policy import ADAPTIVE, FIXED
from execution import Journal, OutputLease, atomic_json
from frontier_common import json_fingerprint, load_jsonl
from frontier_rollout import rollout_record
from run_stage import HERE, B1, TARGET, execution_contract, stage_config, audit, audit_record, reusable


class MissingPrefix(Exception):
    pass


def migrate(source, destination, records, runtime):
    source, destination = Path(source).resolve(), Path(destination).resolve()
    if source == destination:
        raise RuntimeError('migration requires a new destination')
    destination.parent.mkdir(parents=True, exist_ok=True)
    with OutputLease(destination), contextlib.ExitStack() as locks:
        if destination.exists():
            raise RuntimeError('destination exists; refusing to overwrite migration or live state')
        for name in ('allocation.lock', 'owner.lock'):
            lock = locks.enter_context(open(source/name, 'r+'))
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        db = sqlite3.connect((source/'progress.sqlite').as_uri()+'?mode=ro', uri=True)
        try:
            old_contract = json.loads(db.execute("SELECT value FROM meta WHERE key='contract'").fetchone()[0])
            pinned = json.loads((HERE/'migrations/b1_v3_c9ce931.json').read_text())
            expected = dict(stage='b1', input_fingerprint=json_fingerprint(records),
                            scientific_config=stage_config('b1', FIXED), runtime=runtime, code=pinned['code'])
            if old_contract != expected:
                raise RuntimeError('old state does not match the approved v3 code/input/config/runtime contract')
            if json.loads((source/'runtime.json').read_text()) != runtime:
                raise RuntimeError('old runtime manifest differs from checkpoint contract')
            rows = {}
            for key, value, digest in db.execute('SELECT key,value,digest FROM results'):
                parsed = json.loads(value)
                if json_fingerprint(parsed) != digest:
                    raise RuntimeError(f'old checkpoint digest mismatch: {key}')
                rows[key] = parsed
        finally:
            db.close()
        used = set()
        recovered = {}
        complete = []
        old_records = 0
        for record in records:
            cid = record['conversation_id']
            scope = ['b1', cid, json_fingerprint(record)]
            record_key = dict(kind='record', id=cid, input=json_fingerprint(record))
            digest_key = json_fingerprint(record_key)
            old = rows.get(digest_key)
            if old is not None:
                if not reusable('b1', old, record, expected['scientific_config']):
                    raise RuntimeError(f'invalid old completed record: {cid}')
                audit_record('b1', old)
                used.add(digest_key)
                old_records += 1

            class CachedTarget:
                model = TARGET
                def chat_result(self, messages, **kwargs):
                    identity = dict(scope=scope, kind='target', messages=messages, kwargs=kwargs, model=TARGET)
                    key = json_fingerprint(identity)
                    result = rows.get(key)
                    if result is None:
                        raise MissingPrefix(cid)
                    if (result.get('finish_reason') != 'stop' or type(result.get('completion_tokens')) is not int
                        or not 0 < result['completion_tokens'] <= 2048
                        or not isinstance(result.get('content'), str) or not result['content'].strip()):
                        raise RuntimeError(f'invalid old successful target request: {cid}')
                    used.add(key)
                    recovered[key] = (copy.deepcopy(identity), result)
                    return copy.deepcopy(result)

            try:
                reconstructed = rollout_record(record, CachedTarget(), **B1)
            except MissingPrefix:
                if old is not None:
                    raise RuntimeError(f'completed record lacks reconstructible target prefix: {cid}')
                continue
            if old is not None and old != reconstructed:
                raise RuntimeError(f'old record differs from exact cached request reconstruction: {cid}')
            # This only traverses the original 2048-token successful requests.
            # No larger-budget response is inferred or generated by migration.
            upgraded = rollout_record(record, CachedTarget(), budget_policy=ADAPTIVE, **B1)
            audit_record('b1', upgraded)
            complete.append((record_key, upgraded))
        if used != set(rows):
            raise RuntimeError(f'{len(set(rows)-used)} unrecognized/unreachable old cache entries')
        if complete:
            # Full rollout audit also checks runtime fields, seeds and transcript budgets.
            with tempfile.TemporaryDirectory(dir=destination.parent) as audit_dir:
                from execution import atomic_jsonl
                candidate = Path(audit_dir)/'records.jsonl'
                atomic_jsonl(candidate, [value for _,value in complete])
                audit('b1', candidate, len(complete))
        contract = execution_contract('b1', records, runtime, ADAPTIVE)
        temporary = Path(tempfile.mkdtemp(prefix=destination.name+'.migration-', dir=destination.parent))
        try:
            journal = Journal(temporary, contract)
            try:
                for identity, value in recovered.values():
                    journal.put(identity, value)
                for identity, value in complete:
                    journal.put(identity, value)
            finally:
                journal.close()
            atomic_json(temporary/'runtime.json', runtime)
            report = dict(protocol='checked_b1_v3_to_v4_migration_v1', source=str(source),
                source_commit=pinned['commit'], source_contract_fingerprint=json_fingerprint(old_contract),
                destination_contract_fingerprint=json_fingerprint(contract),
                source_result_digests_fingerprint=json_fingerprint({k:json_fingerprint(v) for k,v in rows.items()}),
                original_complete_records=old_records, recovered_complete_records=len(complete),
                recovered_target_requests=len(recovered), input_records=len(records),
                target_budget_policy=ADAPTIVE, original_state_modified=False)
            atomic_json(temporary/'migration.json', report)
            os.rename(temporary, destination)
            directory = os.open(destination.parent, os.O_RDONLY | os.O_DIRECTORY)
            try:os.fsync(directory)
            finally:os.close(directory)
        finally:
            if temporary.exists():shutil.rmtree(temporary)
        return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-state', required=True)
    parser.add_argument('--destination-state', required=True)
    parser.add_argument('--input', required=True)
    parser.add_argument('--mode', choices=['production','smoke'], default='production')
    parser.add_argument('--expected-records', type=int)
    args = parser.parse_args()
    expected = args.expected_records or (3000 if args.mode=='production' else 20)
    if expected < 1 or (args.mode=='production' and expected!=3000):
        raise RuntimeError('production requires exactly 3000 records')
    records = load_jsonl(args.input)
    if len(records)!=expected:
        raise RuntimeError(f'expected {expected} records, found {len(records)}')
    command = [sys.executable,str(HERE/'audit_frontier_source.py'),'--input',args.input]
    command += (['--expected-records','3000','--expected-pairs','1200','--expected-standalone','600','--expected-scenarios','600']
                if args.mode=='production' else ['--schema-only'])
    subprocess.run(command, check=True)
    runtime = json.loads((Path(args.source_state)/'runtime.json').read_text())
    if runtime.get('stage')!='b1' or runtime.get('runtime_determinism')!='vllm_batch_invariant_eager_v1':
        raise RuntimeError('migration requires deterministic B1 runtime')
    print(json.dumps(migrate(args.source_state, args.destination_state, records, runtime), indent=2))
    print('B1 STATE MIGRATION PASSED; original state preserved')


if __name__ == '__main__':main()
